/* Generated By:JavaCC: Do not edit this line. CriterionParserTreeConstants.java Version 4.1 */
package org.betaconceptframework.astroboa.model.impl.query.parser;

public interface CriterionParserTreeConstants
{
  public int JJTCONDITION = 0;
  public int JJTQUERYOPERATOR = 1;
  public int JJTNULLORNOTNULLQUERYOPERATOR = 2;
  public int JJTGETPROPERTY = 3;
  public int JJTGETVALUE = 4;
  public int JJTSIMPLECRITERION = 5;
  public int JJTPRIMARYCRITERION = 6;
  public int JJTFULLCRITERION = 7;
  public int JJTPARENCRITERION = 8;
  public int JJTEXPRESSION = 9;
  public int JJTCRITERION = 10;
  public int JJTUNIFIEDCRITERION = 11;


  public String[] jjtNodeName = {
    "Condition",
    "QueryOperator",
    "NullOrNotNullQueryOperator",
    "GetProperty",
    "GetValue",
    "SimpleCriterion",
    "PrimaryCriterion",
    "FullCriterion",
    "ParenCriterion",
    "Expression",
    "Criterion",
    "UnifiedCriterion",
  };
}
/* JavaCC - OriginalChecksum=b8b3c075d864dc1aba8c79fb21109791 (do not edit this line) */
