/* Generated By:JJTree&JavaCC: Do not edit this line. CriterionParserConstants.java */
package  org.betaconceptframework.astroboa.model.impl.query.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CriterionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NCName = 5;
  /** RegularExpression Id. */
  int Nmstart = 6;
  /** RegularExpression Id. */
  int Nmchar = 7;
  /** RegularExpression Id. */
  int Digit = 8;
  /** RegularExpression Id. */
  int Letter = 9;
  /** RegularExpression Id. */
  int BaseChar = 10;
  /** RegularExpression Id. */
  int Ideographic = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int LPAREN = 14;
  /** RegularExpression Id. */
  int RPAREN = 15;
  /** RegularExpression Id. */
  int LIKE = 16;
  /** RegularExpression Id. */
  int EQUALS = 17;
  /** RegularExpression Id. */
  int NOT_EQUALS = 18;
  /** RegularExpression Id. */
  int GREATER = 19;
  /** RegularExpression Id. */
  int LESS = 20;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 21;
  /** RegularExpression Id. */
  int LESS_EQUAL = 22;
  /** RegularExpression Id. */
  int IS_NULL = 23;
  /** RegularExpression Id. */
  int IS_NOT_NULL = 24;
  /** RegularExpression Id. */
  int CONTAINS = 25;
  /** RegularExpression Id. */
  int PROPERTY_PATH = 26;
  /** RegularExpression Id. */
  int VALUE = 27;
  /** RegularExpression Id. */
  int StringLiteral = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NCName>",
    "<Nmstart>",
    "<Nmchar>",
    "<Digit>",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<AND>",
    "<OR>",
    "\"(\"",
    "\")\"",
    "\"%%\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"IS_NULL\"",
    "\"IS_NOT_NULL\"",
    "\"CONTAINS\"",
    "<PROPERTY_PATH>",
    "<VALUE>",
    "<StringLiteral>",
  };

}
