//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 15:01:08 EEST 
//


package org.betaconceptframework.astroboa.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JcrCacheType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JcrCacheType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="maxMemory" type="{http://www.w3.org/2001/XMLSchema}int" default="256" />
 *       &lt;attribute name="maxMemoryPerCache" type="{http://www.w3.org/2001/XMLSchema}int" default="4" />
 *       &lt;attribute name="minMemoryPerCache" type="{http://www.w3.org/2001/XMLSchema}int" default="128" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JcrCacheType")
public class JcrCacheType {

    @XmlAttribute(name = "maxMemory")
    protected Integer maxMemory;
    @XmlAttribute(name = "maxMemoryPerCache")
    protected Integer maxMemoryPerCache;
    @XmlAttribute(name = "minMemoryPerCache")
    protected Integer minMemoryPerCache;

    /**
     * Gets the value of the maxMemory property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxMemory() {
        if (maxMemory == null) {
            return  256;
        } else {
            return maxMemory;
        }
    }

    /**
     * Sets the value of the maxMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxMemory(Integer value) {
        this.maxMemory = value;
    }

    /**
     * Gets the value of the maxMemoryPerCache property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxMemoryPerCache() {
        if (maxMemoryPerCache == null) {
            return  4;
        } else {
            return maxMemoryPerCache;
        }
    }

    /**
     * Sets the value of the maxMemoryPerCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxMemoryPerCache(Integer value) {
        this.maxMemoryPerCache = value;
    }

    /**
     * Gets the value of the minMemoryPerCache property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMinMemoryPerCache() {
        if (minMemoryPerCache == null) {
            return  128;
        } else {
            return minMemoryPerCache;
        }
    }

    /**
     * Sets the value of the minMemoryPerCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinMemoryPerCache(Integer value) {
        this.minMemoryPerCache = value;
    }

}
