//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 15:01:08 EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.betaconceptframework.org/schema/astroboa/configuration/repositories")
package org.betaconceptframework.astroboa.configuration;
