//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.21 at 03:31:08 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.betaconceptframework.org/schema/astroboa/configuration/repositories")
package org.betaconceptframework.astroboa.configuration;
