//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.19 at 09:44:46 μμ EET 
//


package org.betaconceptframework.astroboa.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RepositoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RepositoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="localization" type="{http://www.betaconceptframework.org/schema/astroboa/configuration/repositories}LocalizationType" minOccurs="0"/>
 *         &lt;element name="security" type="{http://www.betaconceptframework.org/schema/astroboa/configuration/repositories}SecurityType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="jcr-repository-jndi-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="db-jndi-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serverAliasURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="restfulApiBasePath" type="{http://www.w3.org/2001/XMLSchema}string" default="/content-api" />
 *       &lt;attribute name="jaasApplicationPolicyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="authenticationTokenTimeout" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="identity-store-repository-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="external-identity-store-jndi-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepositoryType", propOrder = {
    "localization",
    "security"
})
public class RepositoryType {

    protected LocalizationType localization;
    @XmlElement(required = true)
    protected SecurityType security;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "jcr-repository-jndi-name", required = true)
    protected String jcrRepositoryJndiName;
    @XmlAttribute(name = "db-jndi-name", required = true)
    protected String dbJndiName;
    @XmlAttribute(name = "serverAliasURL")
    @XmlSchemaType(name = "anyURI")
    protected String serverAliasURL;
    @XmlAttribute(name = "restfulApiBasePath")
    protected String restfulApiBasePath;
    @XmlAttribute(name = "jaasApplicationPolicyName")
    protected String jaasApplicationPolicyName;
    @XmlAttribute(name = "authenticationTokenTimeout")
    protected Integer authenticationTokenTimeout;
    @XmlAttribute(name = "identity-store-repository-id")
    protected String identityStoreRepositoryId;
    @XmlAttribute(name = "external-identity-store-jndi-name")
    protected String externalIdentityStoreJndiName;

    /**
     * Gets the value of the localization property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizationType }
     *     
     */
    public LocalizationType getLocalization() {
        return localization;
    }

    /**
     * Sets the value of the localization property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizationType }
     *     
     */
    public void setLocalization(LocalizationType value) {
        this.localization = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityType }
     *     
     */
    public SecurityType getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityType }
     *     
     */
    public void setSecurity(SecurityType value) {
        this.security = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the jcrRepositoryJndiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJcrRepositoryJndiName() {
        return jcrRepositoryJndiName;
    }

    /**
     * Sets the value of the jcrRepositoryJndiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJcrRepositoryJndiName(String value) {
        this.jcrRepositoryJndiName = value;
    }

    /**
     * Gets the value of the dbJndiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbJndiName() {
        return dbJndiName;
    }

    /**
     * Sets the value of the dbJndiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbJndiName(String value) {
        this.dbJndiName = value;
    }

    /**
     * Gets the value of the serverAliasURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerAliasURL() {
        return serverAliasURL;
    }

    /**
     * Sets the value of the serverAliasURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerAliasURL(String value) {
        this.serverAliasURL = value;
    }

    /**
     * Gets the value of the restfulApiBasePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestfulApiBasePath() {
        if (restfulApiBasePath == null) {
            return "/content-api";
        } else {
            return restfulApiBasePath;
        }
    }

    /**
     * Sets the value of the restfulApiBasePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestfulApiBasePath(String value) {
        this.restfulApiBasePath = value;
    }

    /**
     * Gets the value of the jaasApplicationPolicyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJaasApplicationPolicyName() {
        return jaasApplicationPolicyName;
    }

    /**
     * Sets the value of the jaasApplicationPolicyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJaasApplicationPolicyName(String value) {
        this.jaasApplicationPolicyName = value;
    }

    /**
     * Gets the value of the authenticationTokenTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAuthenticationTokenTimeout() {
        return authenticationTokenTimeout;
    }

    /**
     * Sets the value of the authenticationTokenTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAuthenticationTokenTimeout(Integer value) {
        this.authenticationTokenTimeout = value;
    }

    /**
     * Gets the value of the identityStoreRepositoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentityStoreRepositoryId() {
        return identityStoreRepositoryId;
    }

    /**
     * Sets the value of the identityStoreRepositoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentityStoreRepositoryId(String value) {
        this.identityStoreRepositoryId = value;
    }

    /**
     * Gets the value of the externalIdentityStoreJndiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalIdentityStoreJndiName() {
        return externalIdentityStoreJndiName;
    }

    /**
     * Sets the value of the externalIdentityStoreJndiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalIdentityStoreJndiName(String value) {
        this.externalIdentityStoreJndiName = value;
    }

}
