//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.06 at 11:49:26 πμ EET 
//


package org.betaconceptframework.astroboa.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecurityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="permanentUserKeyList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="permanentUserKey" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="userid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="secretUserKeyList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="administratorSecretKey">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="userid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="key" use="required" type="{http://www.betaconceptframework.org/schema/astroboa/configuration/repositories}secretKeyType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="secretUserKey" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="userid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="key" use="required" type="{http://www.betaconceptframework.org/schema/astroboa/configuration/repositories}secretKeyType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityType", propOrder = {
    "permanentUserKeyList",
    "secretUserKeyList"
})
public class SecurityType {

    protected SecurityType.PermanentUserKeyList permanentUserKeyList;
    @XmlElement(required = true)
    protected SecurityType.SecretUserKeyList secretUserKeyList;

    /**
     * Gets the value of the permanentUserKeyList property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityType.PermanentUserKeyList }
     *     
     */
    public SecurityType.PermanentUserKeyList getPermanentUserKeyList() {
        return permanentUserKeyList;
    }

    /**
     * Sets the value of the permanentUserKeyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityType.PermanentUserKeyList }
     *     
     */
    public void setPermanentUserKeyList(SecurityType.PermanentUserKeyList value) {
        this.permanentUserKeyList = value;
    }

    /**
     * Gets the value of the secretUserKeyList property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityType.SecretUserKeyList }
     *     
     */
    public SecurityType.SecretUserKeyList getSecretUserKeyList() {
        return secretUserKeyList;
    }

    /**
     * Sets the value of the secretUserKeyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityType.SecretUserKeyList }
     *     
     */
    public void setSecretUserKeyList(SecurityType.SecretUserKeyList value) {
        this.secretUserKeyList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="permanentUserKey" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="userid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "permanentUserKey"
    })
    public static class PermanentUserKeyList {

        @XmlElement(required = true)
        protected List<SecurityType.PermanentUserKeyList.PermanentUserKey> permanentUserKey;

        /**
         * Gets the value of the permanentUserKey property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the permanentUserKey property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPermanentUserKey().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SecurityType.PermanentUserKeyList.PermanentUserKey }
         * 
         * 
         */
        public List<SecurityType.PermanentUserKeyList.PermanentUserKey> getPermanentUserKey() {
            if (permanentUserKey == null) {
                permanentUserKey = new ArrayList<SecurityType.PermanentUserKeyList.PermanentUserKey>();
            }
            return this.permanentUserKey;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="userid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class PermanentUserKey {

            @XmlAttribute(name = "userid", required = true)
            protected String userid;
            @XmlAttribute(name = "key", required = true)
            protected String key;

            /**
             * Gets the value of the userid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserid() {
                return userid;
            }

            /**
             * Sets the value of the userid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserid(String value) {
                this.userid = value;
            }

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="administratorSecretKey">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="userid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="key" use="required" type="{http://www.betaconceptframework.org/schema/astroboa/configuration/repositories}secretKeyType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="secretUserKey" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="userid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="key" use="required" type="{http://www.betaconceptframework.org/schema/astroboa/configuration/repositories}secretKeyType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "administratorSecretKey",
        "secretUserKey"
    })
    public static class SecretUserKeyList {

        @XmlElement(required = true)
        protected SecurityType.SecretUserKeyList.AdministratorSecretKey administratorSecretKey;
        protected List<SecurityType.SecretUserKeyList.SecretUserKey> secretUserKey;

        /**
         * Gets the value of the administratorSecretKey property.
         * 
         * @return
         *     possible object is
         *     {@link SecurityType.SecretUserKeyList.AdministratorSecretKey }
         *     
         */
        public SecurityType.SecretUserKeyList.AdministratorSecretKey getAdministratorSecretKey() {
            return administratorSecretKey;
        }

        /**
         * Sets the value of the administratorSecretKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link SecurityType.SecretUserKeyList.AdministratorSecretKey }
         *     
         */
        public void setAdministratorSecretKey(SecurityType.SecretUserKeyList.AdministratorSecretKey value) {
            this.administratorSecretKey = value;
        }

        /**
         * Gets the value of the secretUserKey property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the secretUserKey property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSecretUserKey().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SecurityType.SecretUserKeyList.SecretUserKey }
         * 
         * 
         */
        public List<SecurityType.SecretUserKeyList.SecretUserKey> getSecretUserKey() {
            if (secretUserKey == null) {
                secretUserKey = new ArrayList<SecurityType.SecretUserKeyList.SecretUserKey>();
            }
            return this.secretUserKey;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="userid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="key" use="required" type="{http://www.betaconceptframework.org/schema/astroboa/configuration/repositories}secretKeyType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AdministratorSecretKey {

            @XmlAttribute(name = "userid", required = true)
            protected String userid;
            @XmlAttribute(name = "key", required = true)
            protected String key;

            /**
             * Gets the value of the userid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserid() {
                return userid;
            }

            /**
             * Sets the value of the userid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserid(String value) {
                this.userid = value;
            }

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="userid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="key" use="required" type="{http://www.betaconceptframework.org/schema/astroboa/configuration/repositories}secretKeyType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SecretUserKey {

            @XmlAttribute(name = "userid", required = true)
            protected String userid;
            @XmlAttribute(name = "key", required = true)
            protected String key;

            /**
             * Gets the value of the userid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserid() {
                return userid;
            }

            /**
             * Sets the value of the userid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserid(String value) {
                this.userid = value;
            }

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

        }

    }

}
