//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.25 at 12:12:18 �� EEST 
//


package org.betaconceptframework.astroboa.model.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import org.betaconceptframework.astroboa.model.factory.CmsRepositoryEntityFactoryForActiveClient;
import org.betaconceptframework.astroboa.model.jaxb.type.BinaryChannelType;
import org.betaconceptframework.astroboa.model.jaxb.type.ComplexCmsPropertyType;
import org.betaconceptframework.astroboa.model.jaxb.type.ContentObjectType;
import org.betaconceptframework.astroboa.model.jaxb.type.LocalizationType;
import org.betaconceptframework.astroboa.model.jaxb.type.SimpleCmsPropertyType;
import org.betaconceptframework.astroboa.model.jaxb.type.SpaceType;
import org.betaconceptframework.astroboa.model.jaxb.type.TopicType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.betaconceptframework.astroboa.model.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Space_QNAME = new QName("http://www.betaconceptframework.org/schema/astroboa/model", "space");
    private final static QName _Taxonomy_QNAME = new QName("http://www.betaconceptframework.org/schema/astroboa/model", "taxonomy");
    private final static QName _RepositoryUser_QNAME = new QName("http://www.betaconceptframework.org/schema/astroboa/model", "repositoryUser");
    private final static QName _Topic_QNAME = new QName("http://www.betaconceptframework.org/schema/astroboa/model", "topic");

    public ObjectFactory() {
    	
    }

    @XmlElementDecl(namespace = "http://www.betaconceptframework.org/schema/astroboa/model", name = "taxonomy")
    public JAXBElement<TaxonomyImpl> createTaxonomyElement() {
        return new JAXBElement<TaxonomyImpl>(_Taxonomy_QNAME, TaxonomyImpl.class, null, (TaxonomyImpl)CmsRepositoryEntityFactoryForActiveClient.INSTANCE.getFactory().newTaxonomy());
    }

    @XmlElementDecl(namespace = "http://www.betaconceptframework.org/schema/astroboa/model", name = "topic")
    public JAXBElement<TopicImpl> createTopicElement() {
        return new JAXBElement<TopicImpl>(_Topic_QNAME, TopicImpl.class, null, (TopicImpl)CmsRepositoryEntityFactoryForActiveClient.INSTANCE.getFactory().newTopic());
    }
    
    @XmlElementDecl(namespace = "http://www.betaconceptframework.org/schema/astroboa/model", name = "space")
    public JAXBElement<SpaceImpl> createSpaceElement() {
        return new JAXBElement<SpaceImpl>(_Space_QNAME, SpaceImpl.class, null, (SpaceImpl)CmsRepositoryEntityFactoryForActiveClient.INSTANCE.getFactory().newSpace());
    }
    
    @XmlElementDecl(namespace = "http://www.betaconceptframework.org/schema/astroboa/model", name = "repositoryUser")
    public JAXBElement<RepositoryUserImpl> createRepositoryUserElement() {
        return new JAXBElement<RepositoryUserImpl>(_RepositoryUser_QNAME, RepositoryUserImpl.class, null, (RepositoryUserImpl)CmsRepositoryEntityFactoryForActiveClient.INSTANCE.getFactory().newRepositoryUser());
    }
    
    /**
     * Create an instance of {@link BinaryChannelType }
     * 
     */
    public BinaryChannelType createBinaryChannelType() {
        return new BinaryChannelType();
    }
    
    /**
     * Create an instance of {@link ContentObjectType }
     * 
     */
    public ContentObjectType createContentObjectType() {
        return new ContentObjectType();
    }
    
    /**
     * Create an instance of {@link SimpleCmsPropertyType }
     * 
     */
    public SimpleCmsPropertyType createSimpleCmsPropertyType() {
        return new SimpleCmsPropertyType();
    }
    
    /**
     * Create an instance of {@link ComplexCmsPropertyType }
     * 
     */
    public ComplexCmsPropertyType createCompelxCmsPropertyType() {
        return new ComplexCmsPropertyType();
    }
    
    /**
     * Create an instance of {@link TopicType }
     * 
     */
    public TopicType createTopicType() {
        return new TopicType();
    }
    
    /**
     * Create an instance of {@link SpaceType }
     * 
     */
    public SpaceType createSpaceType() {
        return new SpaceType();
    }
    
    /**
     * Create an instance of {@link LocalizationType }
     * 
     */
    public LocalizationType createLocalizationType() {
        return new LocalizationType();
    }

    /**
     * Create an instance of {@link LocalizationType.Label }
     * 
     */
    public LocalizationType.Label createLocalizationTypeLocalizedLabel() {
        return new LocalizationType.Label();
    }
    
}
