//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.25 at 12:12:18 �� EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.betaconceptframework.org/schema/astroboa/model")
package org.betaconceptframework.astroboa.model.impl;
