/*
 * Copyright (C) 2005-2011 BetaCONCEPT LP_
 *
 * This file is part of Astroboa.
 *
 * Astroboa is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version_
 *
 * Astroboa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE_  See the
 * GNU General Public License for more details_
 *
 * You should have received a copy of the GNU General Public License
 * along with Astroboa  If not, see <http://www_gnu_org/licenses/>_
 */
package org.betaconceptframework.astroboa.test.engine;

/**
 * All possible property paths for content type test
 * 
 * @author Gregory Chomatas (gchomatas@betaconcept_com)
 * @author Savvas Triantafyllou (striantafyllou@betaconcept_com)
 * 
 */
public enum CmsPropertyPath {
	
	//ValueType_String
	stringEnum,
	commentSingle_body,
	commentSingle_bodyMultiple,
	comment_body,
	comment_bodyMultiple,
	allPropertyTypeContainer_comment_body,
	allPropertyTypeContainer_comment_bodyMultiple,
	allPropertyTypeContainer_commentMultiple_body,
	allPropertyTypeContainer_commentMultiple_bodyMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_commentMultiple_body,
	allPropertyTypeContainer_allPropertyTypeContainer_commentMultiple_bodyMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_comment_body,
	allPropertyTypeContainer_allPropertyTypeContainer_comment_bodyMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_comment_body,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_comment_bodyMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_commentMultiple_body,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_commentMultiple_bodyMultiple,
	allPropertyTypeContainerMultiple_comment_body,
	allPropertyTypeContainerMultiple_comment_bodyMultiple,
	allPropertyTypeContainerMultiple_commentMultiple_body,
	allPropertyTypeContainerMultiple_commentMultiple_bodyMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_comment_body,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_comment_bodyMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_commentMultiple_body,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_commentMultiple_bodyMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_comment_body,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_comment_bodyMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_commentMultiple_body,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_commentMultiple_bodyMultiple,
	simpleString,
	allPropertyTypeContainer_simpleString,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleString,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleString,
	allPropertyTypeContainerMultiple_simpleString,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleString,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleString,
	simpleStringMultiple,
	allPropertyTypeContainer_simpleStringMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleStringMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleStringMultiple,
	allPropertyTypeContainerMultiple_simpleStringMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleStringMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleStringMultiple,
	password,
	passwordWithExternalPasswordEncryptor,

	//ValueType_Long
	longEnum,
	simpleLong,
	allPropertyTypeContainer_simpleLong,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleLong,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleLong,
	allPropertyTypeContainerMultiple_simpleLong,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleLong,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleLong,
	simpleLongMultiple,
	allPropertyTypeContainer_simpleLongMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleLongMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleLongMultiple,
	allPropertyTypeContainerMultiple_simpleLongMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleLongMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleLongMultiple,

	
	//ValueType_Double;
	doubleEnum,
	simpleDouble,
	allPropertyTypeContainer_simpleDouble,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleDouble,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleDouble,
	allPropertyTypeContainerMultiple_simpleDouble,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleDouble,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleDouble,
	simpleDoubleMultiple,
	allPropertyTypeContainer_simpleDoubleMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleDoubleMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleDoubleMultiple,
	allPropertyTypeContainerMultiple_simpleDoubleMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleDoubleMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleDoubleMultiple,

	
	//ValueType_Binary;
	thumbnail,
	image,
	simpleBinary,
	allPropertyTypeContainer_simpleBinary,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleBinary,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleBinary,
	allPropertyTypeContainerMultiple_simpleBinary,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleBinary,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleBinary,
	simpleBinaryMultiple,
	allPropertyTypeContainer_simpleBinaryMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleBinaryMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleBinaryMultiple,
	allPropertyTypeContainerMultiple_simpleBinaryMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleBinaryMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleBinaryMultiple,
	
	//ValueType_Boolean;
	simpleBoolean,
	allPropertyTypeContainer_simpleBoolean,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleBoolean,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleBoolean,
	allPropertyTypeContainerMultiple_simpleBoolean,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleBoolean,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleBoolean,
	simpleBooleanMultiple,
	allPropertyTypeContainer_simpleBooleanMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleBooleanMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleBooleanMultiple,
	allPropertyTypeContainerMultiple_simpleBooleanMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleBooleanMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleBooleanMultiple,

	
	//ValueType_ContentObject;
	simpleContentObject,
	allPropertyTypeContainer_simpleContentObject,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleContentObject,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleContentObject,
	allPropertyTypeContainerMultiple_simpleContentObject,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleContentObject,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleContentObject,
	simpleContentObjectMultiple,
	allPropertyTypeContainer_simpleContentObjectMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleContentObjectMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleContentObjectMultiple,
	allPropertyTypeContainerMultiple_simpleContentObjectMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleContentObjectMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleContentObjectMultiple,
	
	//ValueType_Date;
	simpleDate,
	allPropertyTypeContainer_simpleDate,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleDate,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleDate,
	allPropertyTypeContainerMultiple_simpleDate,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleDate,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleDate,
	simpleDateTime,
	allPropertyTypeContainer_simpleDateTime,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleDateTime,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleDateTime,
	allPropertyTypeContainerMultiple_simpleDateTime,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleDateTime,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleDateTime,
	simpleDateMultiple,
	allPropertyTypeContainer_simpleDateMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleDateMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleDateMultiple,
	allPropertyTypeContainerMultiple_simpleDateMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleDateMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleDateMultiple,
	simpleDateTimeMultiple,
	allPropertyTypeContainer_simpleDateTimeMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleDateTimeMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleDateTimeMultiple,
	allPropertyTypeContainerMultiple_simpleDateTimeMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleDateTimeMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleDateTimeMultiple,


	
	//ValueType_Topic
	simpleTopic,
	allPropertyTypeContainer_simpleTopic,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleTopic,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleTopic,
	allPropertyTypeContainerMultiple_simpleTopic,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleTopic,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleTopic,
	simpleTopicMultiple,
	allPropertyTypeContainer_simpleTopicMultiple,
	allPropertyTypeContainer_allPropertyTypeContainer_simpleTopicMultiple,
	allPropertyTypeContainer_allPropertyTypeContainerMultiple_simpleTopicMultiple,
	allPropertyTypeContainerMultiple_simpleTopicMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainerMultiple_simpleTopicMultiple,
	allPropertyTypeContainerMultiple_allPropertyTypeContainer_simpleTopicMultiple,

	//ValueType_Complex - Aspects
	statisticTypeMultiple,
	statisticType;

	public String getPeriodDelimitedPath()
	{
		return this.toString().replaceAll("_", "\\.");
	}
}
