//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.20 at 08:34:05 EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.betaconceptframework.org/schema/astroboa/api")
package org.betaconceptframework.astroboa.engine.model.jaxb;
